# Generated by Django 5.1.7 on 2025-03-30 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=20, verbose_name='Recurrence Type')),
                ('interval', models.PositiveIntegerField(default=1, verbose_name='Interval (e.g., every X days/weeks/months)')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=255, verbose_name='Event Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='Event Day (No time)')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, default='01:00:00', null=True, verbose_name='End Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('recurrence_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='Glassync.recurrencerule', verbose_name='Recurrence Rule')),
            ],
        ),
    ]
