# Generated by Django 5.1.7 on 2025-03-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glassync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('week_days', models.JSONField(blank=True, null=True)),
                ('month_day', models.IntegerField(blank=True, null=True)),
                ('year_day', models.DateField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rule_set', to='Glassync.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='Glassync.recurrencerule'),
        ),
        migrations.DeleteModel(
            name='RecurringEvent',
        ),
    ]
