# Generated by Django 5.1.7 on 2025-03-30 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glassync', '0003_remove_event_created_at_remove_event_recurrence_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='event',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='month_day',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='recurrence_type',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='week_days',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='year_day',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Event Day (No time)'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Untitled', max_length=255, verbose_name='Event Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='Glassync.recurrencerule', verbose_name='Recurrence Rule'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=20, verbose_name='Recurrence Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default='01:00:00', null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='interval',
            field=models.PositiveIntegerField(default=1, verbose_name='Interval (e.g., every X days/weeks/months)'),
        ),
    ]
